version: "3"
services:

    # app
    authentication-server:
        image: elyspio/authentication:latest
        container_name: authentication-server
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=external"
            - "traefik.http.middlewares.authentication-prefix.stripprefix.prefixes=/authentication"
            - "traefik.http.routers.authentication.middlewares=authentication-prefix@docker"
            - "traefik.http.routers.authentication.rule=PathPrefix(`/authentication`)"
            - "traefik.http.services.authentication.loadbalancer.server.port=4000"
            - "traefik.http.routers.authentication.entrypoints=external"

        environment:
            DB_PASSWORD: "Azeqsdwxc123"
            DB_HOST: authentication-db
            DB_USERNAME: "root"
            DB_PORT: 27017
            DB_DATABASE: admin
            HTTP_PORT: 4000
        volumes:
            - ./config/front/conf.js:/front/conf.js
        depends_on:
            - authentication-db
        networks:
            - authentication
            - external

    # database
    authentication-db:
        image: mongo:latest
        labels:
            - "traefik.enable=false"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: Azeqsdwxc123
        volumes:
            - ./data:/data/db
        networks:
            - internal
            - authentication

networks:
    authentication:
        name: "authentication"
    external:
        external: true
    internal:
        external: true

