version: "3"
services:

    # app
    authentication-server:
        image: elyspio/authentication:latest
        container_name: authentication-server
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=frontend"
            - "traefik.http.middlewares.authentication-prefix.stripprefix.prefixes=/authentication"
            - "traefik.http.routers.authentication.middlewares=authentication-prefix@docker"
            - "traefik.http.routers.authentication.rule=PathPrefix(`/authentication`)"
            - "traefik.http.services.authentication.loadbalancer.server.port=4000"
            - "traefik.http.routers.authentication.entrypoints=http"

        environment:
            DB_PASSWORD: "Azeqsdwxc123"
            DB_HOST: authentication-db
            DB_USERNAME: "postgres"
            DB_PORT: 5432
            DB_DATABASE: authentication
        volumes:
            - ./config/front/conf.js:/front/conf.js
        depends_on:
            - authentication-db
        networks:
            - authentication
            - frontend

    # database
    authentication-db:
        image: postgres:alpine
        container_name: authentication-database
        environment:
            - POSTGRES_PASSWORD=Azeqsdwxc123
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - './data/db:/var/lib/postgresql/data'
        networks:
            - authentication

networks:
    authentication:
        name: "authentication"
    frontend:
        external: true

