version: "3"
services:

    # app
    authentication-server:
        image: elyspio/authentication:latest
        container_name: authentication-server
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=external"
            - "traefik.http.middlewares.authentication-prefix.stripprefix.prefixes=/authentication"
            - "traefik.http.routers.authentication.middlewares=authentication-prefix@docker"
            - "traefik.http.routers.authentication.rule=PathPrefix(`/authentication`)"
            - "traefik.http.services.authentication.loadbalancer.server.port=4000"
            - "traefik.http.routers.authentication.entrypoints=external"
        volumes:
            - ./config/front/conf.js:/front/conf.js
            - ./config/back/external.json:/back/build/config/external.json
        networks:
            - authentication
            - external
            - internal

networks:
    authentication:
        name: "authentication"
    external:
        external: true
    internal:
        external: true


