version: '3.7'
services:
    reverse-proxy:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        container_name: authentication-dev-proxy

    authentication-db:
        image: postgres:alpine
        container_name: authentication-dev-database
        environment:
            - POSTGRES_PASSWORD=mysecretpassword
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - './data/db:/var/lib/postgresql/data'
        ports:
            - "5432:5432"
